SET GLOBAL event_scheduler = ON;

DROP EVENT IF EXISTS ejecuta_taulestime;

DELIMITER //

CREATE EVENT ejecuta_taulestime
ON SCHEDULE EVERY 30 SECOND
    STARTS CURRENT_TIMESTAMP
    ENDS CURRENT_TIMESTAMP + INTERVAL 3 MINUTE
    ON COMPLETION PRESERVE
DO
    BEGIN
        CALL taulestime();
    END //
DELIMITER ;
