USE mysql;

-- Crear usuaris
CREATE USER 'Venedor1'@'localhost' IDENTIFIED BY 'P@ssw0rd1' PASSWORD EXPIRE INTERVAL 60 DAY FAILED_LOGIN_ATTEMPTS 3;
CREATE USER 'Venedor2'@'localhost' IDENTIFIED BY 'P@ssw0rd1' PASSWORD EXPIRE INTERVAL 60 DAY FAILED_LOGIN_ATTEMPTS 3;
CREATE USER 'Venedor3'@'localhost' IDENTIFIED BY 'P@ssw0rd1' PASSWORD EXPIRE INTERVAL 60 DAY FAILED_LOGIN_ATTEMPTS 3;

CREATE USER 'Director1'@'localhost' IDENTIFIED BY 'P@ssw0rd2' PASSWORD EXPIRE INTERVAL 3 DAY FAILED_LOGIN_ATTEMPTS 2 ACCOUNT LOCK;
CREATE USER 'Director2'@'localhost' IDENTIFIED BY 'P@ssw0rd2' PASSWORD EXPIRE INTERVAL 3 DAY FAILED_LOGIN_ATTEMPTS 2 ACCOUNT LOCK;

CREATE USER 'Gerent'@'localhost' IDENTIFIED BY 'P@ssw0rd3' FAILED_LOGIN_ATTEMPTS 2 ACCOUNT LOCK PASSWORD EXPIRE INTERVAL 1 DAY;

-- Mostrar informació dels usuarios creats per comprovar el correcte funcionament
SELECT *
FROM mysql.user
WHERE User LIKE 'Venedor%' OR User LIKE 'Director%' OR User = 'Gerent';